// Employee Actions
export const EMPLOYEES_FETCH_BY_COMPANY_NAME = 'EMPLOYEES_FETCH_BY_COMPANY_NAME';
export const EMPLOYEES_FETCH_BY_COMPANY_NAME_SUCCESS = 'EMPLOYEES_FETCH_BY_COMPANY_NAME_SUCCESS';
export const EMPLOYEES_FETCH_BY_COMPANY_NAME_FAIL = 'EMPLOYEES_FETCH_BY_COMPANY_NAME_FAIL';