// Student Actions
export const STUDENT_FETCH_ALL = 'STUDENT_FETCH_ALL';
export const STUDENT_FETCH_ALL_SUCCESS = 'STUDENT_FETCH_ALL_SUCCESS';
export const STUDENT_FETCH_ALL_FAIL = 'STUDENT_FETCH_ALL_FAIL';
export const STUDENT_SEARCH_BY_SKILLS = 'STUDENT_SEARCH_BY_SKILLS';
export const STUDENT_SEARCH_BY_SKILLS_SUCCESS = 'STUDENT_SEARCH_BY_SKILLS_SUCCESS';
export const STUDENT_SEARCH_BY_SKILLS_FAIL = 'STUDENT_SEARCH_BY_SKILLS_FAIL';