// // Company Actions
// export const COMPANY_CREATE = 'COMPANY_CREATE';
// export const COMPANY_CREATE_SUCCESS = 'COMPANY_CREATE_SUCCESS';
// export const COMPANY_CREATE_FAIL = 'COMPANY_CREATE_FAIL';

// export const COMPANY_FETCH_ALL = 'COMPANY_FETCH_ALL';
// export const COMPANY_FETCH_ALL_SUCCESS = 'COMPANY_FETCH_ALL_SUCCESS';
// export const COMPANY_FETCH_ALL_FAIL = 'COMPANY_FETCH_ALL_FAIL';

// export const COMPANY_UPDATE = 'COMPANY_UPDATE';
// export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS';
// export const COMPANY_UPDATE_FAIL = 'COMPANY_UPDATE_FAIL';

// export const COMPANY_DELETE = 'COMPANY_DELETE';
// export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
// export const COMPANY_DELETE_FAIL = 'COMPANY_DELETE_FAIL';

// export const COMPANY_RESET = 'COMPANY_RESET';
